services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/marvin/sonarr_config:/config
      - /mnt/HDD/Media/TV:/tv
      - /mnt/HDD/Media:/media
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/marvin/radarr_config:/config
      - /mnt/HDD/Media/Films:/films
      - /mnt/HDD/Media:/media
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/marvin/prowlarr_config:/config
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/marvin/jellyfin_library:/config
      - /mnt/HDD/Media/TV:/data/tvshows
      - /mnt/HDD/Media/Films:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Tashkent
    volumes:
      - /mnt/HDD/Media/Jellyseer:/app/config
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/HDD/Media:/config
      - /mnt/HDD/Media/Downloads:/downloads
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    ports:
      - 8989:8989 #Sonarr
      - 7878:7878 #Radarr
      - 9696:9696 #Prowlarr
      - 5055:5055 #Jellyseer
      - 8080:8080 #Qbittorrent
      - 6881:6881 #Qbittorrent
      - 6881:6881/udp #Qbittorrent
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=cyberghost
      - OPENVPN_USER=egibifwy2r
      - OPENVPN_PASSWORD=MtcBi3eDhn
      - SERVER_COUNTRIES=United Kingdom
    volumes:
      - /mnt/HDD/Media/config/vpn_cert:/gluetun
