version: '3.8'

services:
  #################################
  ###Sonarr
  #################################

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/marvin/sonarr_config:/config
      - /mnt/HDD/Media/TV:/tv
      - /mnt/HDD/Media:/media
    ports:
      - 8989:8989
    restart: unless-stopped
	
  #################################
  ###Radarr
  #################################

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/marvin/radarr_config:/config
      - /mnt/HDD/Media/Films:/films
      - /mnt/HDD/Media:/media
    ports:
      - 7878:7878
    restart: unless-stopped
	
  #################################
  ###Prowlarr
  #################################

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/marvin/prowlarr_config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
	
  #################################
  ###Jellyfin
  #################################

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    volumes:
      - /home/marvin/jellyfin_library:/config
      - /mnt/HDD/Media/TV:/data/tvshows
      - /mnt/HDD/Media/Films:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
	
  #################################
  ###Jellyseer
  #################################

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Tashkent
    ports:
      - 5055:5055
    volumes:
      - jellyseerr-data:/app/config
    restart: unless-stopped

  #################################
  ###Qbittorrent
  #################################

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/HDD/Media:/config
      - /mnt/HDD/Media/Downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
